reddit/reddit_on_rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => 'accounts'

	root 'pages#index'
	
	resources :users do
		resources :links, only: [:index]
	end
	
	resources :links, only: [:new, :create, :destroy]
	resources :pages
	

end

reddit/reddit_on_rails/app/models/comment.rb
class Comment < ActiveRecord::Base
	
	
	
	belongs_to :commentable, polymorphic: true
	belongs_to :commenter, class_name: "User", foreign_key: :commenter_id, primary_key: :id
	
end

reddit/reddit_on_rails/app/models/link.rb
class Link < ActiveRecord::Base
	
	belongs_to :user, class_name: "User", foreign_key: :user_id, primary_key: :id
	
	has_many :comments, as: :commentable
	has_many :commenters, through: :comments, source: :commentable, source_type: 'Link'
	
end

reddit/reddit_on_rails/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	# links should live on without their submitters
	has_many :links, class_name: "Link", foreign_key: :user_id, primary_key: :id, inverse_of: :user
	# accepts_nested_attributes_for :links
	
	# comments that user makes
	has_many :comments, class_name: "Comment", foreign_key: :commenter_id, inverse_of: :commenter, dependent: :destroy
	
	#comments by others that show up on user's page
	has_many :comments_about, as: :commentable
	# has_many :commenters, through: :comments_about, source: :commentable, source_type: 'User'
	
end

reddit/reddit_on_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	helper_method :is_owner?
	
	def is_owner?(link)
		current_user && link.user == current_user
	end
	
end

reddit/reddit_on_rails/app/controllers/links_controller.rb
class LinksController < ApplicationController
#	decorates_assigned :link
	before_action :authenticate_user!, only: [:new, :create, :destroy]
	before_action :set_link, only: [:edit, :update, :destroy]
	
	def index
		@links = LinkDecorator.decorate_collection(current_user.links)
	end
	
	def new
		@link = Link.new
	end
	
	def create
		@link = current_user.links.build(link_params)
		
		respond_to do |format|
			if @link.save
				format.html { redirect_to user_links_path(current_user), notice: 'Link submitted!' }
				format.js { }
				format.json { render json: @link, status: :created, location: user_links_path }
			else
				format.html do
					flash.now[:errors] = @link.errors.full_messages
					render action: :new 
				end
				format.json { render json: @link.errors.full_messages, status: :unprocessable_entity }
			end
		end
	end
	
	def edit
	end
	
	def update
	end
	
	def destroy	
		if @link.destroy!
			flash[:success] = "Link deleted."
			redirect_to root_url
		else
			flash[:danger] = "Something went wrong."
			redirect_to root_url
		end
	end
	
	private 
	
	def set_link
		@link = Link.find(params[:id])
	end
	
	def link_params
		params.require(:link).permit(:url, :title)
	end
	
	
end

reddit/reddit_on_rails/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def index
		params[:per_page] ||= 5
		params[:page]     ||= 1
	#	@links = Link.order('created_at DESC').page(params[:page])
		#.page(params[:page]).per_page(params[:per_page])
		
		links = Link.order('created_at DESC').paginate(per_page: params[:per_page], page: params[:page])
		@links = LinkDecorator.decorate_collection(links)
		
		respond_to do |format|
   	 	format.html
    	format.json  { render :json => @links }
  	end
	end
	
end

reddit/reddit_on_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit/reddit_on_rails/app/helpers/links_helper.rb
module LinksHelper
	
end

reddit/reddit_on_rails/app/helpers/pages_helper.rb
module PagesHelper
end

reddit/reddit_on_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	  <%# user is logged in, show log out link %>
		<% if current_user.present? %>
			<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
			<%= link_to "Add a link", new_link_path %>
		<%# user is not logged in, show signup and login links %>
		<% else %>
			<%= link_to 'Sign In', new_user_session_path %> |
			<%= link_to 'Register Now!', new_user_registration_path %>
		<% end %>
	
<%= yield %>

<%= p params %>
</body>
</html>

reddit/reddit_on_rails/app/views/links/_form.html.erb
<%= form_for [@current_user, @link], :url => {action: "create", controller: "links"}, html: { method: "POST" } do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :url %><br />
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Post", class: "btn btn-info" %>
  </div>
<% end %>

reddit/reddit_on_rails/app/views/links/_link.html.erb
<ul>
 
	<li><%= link_to "#{link.title}", link.url %> 
		<%= button_to("Delete", link_path(link), method: :delete, form_class: "custom_button_to btn btn-info" ) if is_owner?(link) %>
		<br>
		<%= link_to "comments", link_url(link) %>
	</li>
  
</ul>

reddit/reddit_on_rails/app/views/links/create.html.erb
<!--
To change this template use Tools | Templates.
-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

reddit/reddit_on_rails/app/views/links/index.html.erb
<h1> <%= current_user.username %> </h1>
<h2> My Submissions </h2>

<%= render @links %>

reddit/reddit_on_rails/app/views/links/new.html.erb
<%= render partial: "form" %>

reddit/reddit_on_rails/app/views/links/show.html.erb
<!--
To change this template use Tools | Templates.
-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

reddit/reddit_on_rails/app/views/pages/index.html.erb
<h2>re-reddit</h2>

<%= render partial: "links/link", collection: @links %>
<%= will_paginate @links %>